[package]
name = "game_platform_framework"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.136"
serde_derive = "1.0.136"
laminar = "0.5.0"
bincode = "1.3.3"
